# Script for *www.jobi.tn*

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("jobi.csv")

In [3]:
df.head()

,id,uuid,slug,profile_id,title,category_id,collaborators,description,summary,salary_min,...,tags/1,tags/2,tags/3,weight,tags/4,tags/5,tags/6,tags/7,tags/8,tags/9
0,224796,59239852-7e09-47b9-870a-057753011983,developpeur-web--at--kap-it-tunisia-224796,3088,Développeur web,10,NaN,KAP IT révolutionne la collaboration en entrep...,NaN,NaN,...,java,front-end,angular,3,NaN,NaN,NaN,NaN,NaN,NaN
1,225266,0eda32ff-2ffe-4402-939a-370fe0271392,controleur-de-gestion-reporting-analyst--at--o...,16406,Contrôleur de Gestion Reporting Analyst,10,NaN,ODDO BHF Tunis est une entreprise de services ...,NaN,NaN,...,reporting,gestion,analyst,3,NaN,NaN,NaN,NaN,NaN,NaN
2,225150,b17c6c15-de49-46ea-8609-aa02d0eb91de,ied-java-jee--php-symfony--net--ios--android--...,21353,"IED Java JEE, PHP/Symfony, .NET, IOS, Android,...",67,NaN,Bonjour :)\r\n\r\nJe suis à la recherche de pl...,NaN,NaN,...,angular4,ios,php,3,android,java,NaN,NaN,NaN,NaN
3,225394,6dd6904b-2762-48f3-9947-97434596206d,senior-reactjs-developer--at--weavelines-225394,14035,Senior ReactJS Developer,10,NaN,Company:\r\n\r\nWeaveLines is a digital lab bu...,NaN,NaN,...,redux,reactjs,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN
4,224244,37ce3e65-0160-4663-9c2d-a83c8771cd20,developpeur-php-symfony--at--proxym-group-224244,1017,Développeur PHP/Symfony,58,NaN,"PROXYM Group, leader dans le secteur IT notam...",NaN,1250.0,...,developpement,développement,reporting,3,web,symfony,git,php,html,css

In [4]:
df.head().salary_max

0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
Name: salary_max, dtype: float64

In [5]:
df

,id,uuid,slug,profile_id,title,category_id,collaborators,description,summary,salary_min,...,tags/1,tags/2,tags/3,weight,tags/4,tags/5,tags/6,tags/7,tags/8,tags/9
0,224796,59239852-7e09-47b9-870a-057753011983,developpeur-web--at--kap-it-tunisia-224796,3088,Développeur web,10,NaN,KAP IT révolutionne la collaboration en entrep...,NaN,NaN,...,java,front-end,angular,3,NaN,NaN,NaN,NaN,NaN,NaN
1,225266,0eda32ff-2ffe-4402-939a-370fe0271392,controleur-de-gestion-reporting-analyst--at--o...,16406,Contrôleur de Gestion Reporting Analyst,10,NaN,ODDO BHF Tunis est une entreprise de services ...,NaN,NaN,...,reporting,gestion,analyst,3,NaN,NaN,NaN,NaN,NaN,NaN
2,225150,b17c6c15-de49-46ea-8609-aa02d0eb91de,ied-java-jee--php-symfony--net--ios--android--...,21353,"IED Java JEE, PHP/Symfony, .NET, IOS, Android,...",67,NaN,Bonjour :)\r\n\r\nJe suis à la recherche de pl...,NaN,NaN,...,angular4,ios,php,3,android,java,NaN,NaN,NaN,NaN
3,225394,6dd6904b-2762-48f3-9947-97434596206d,senior-reactjs-developer--at--weavelines-225394,14035,Senior ReactJS Developer,10,NaN,Company:\r\n\r\nWeaveLines is a digital lab bu...,NaN,NaN,...,redux,reactjs,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN
4,224244,37ce3e65-0160-4663-9c2d-a83c8771cd20,developpeur-php-symfony--at--proxym-group-224244,1017,Développeur PHP/Symfony,58,NaN,"PROXYM Group, leader dans le secteur IT notam...",NaN,1250.0,...,developpement,développement,reporting,3,web,symfony,git,php,html,css
5,225905,74952a7b-2b2a-4d56-a446-01e163030160,responsable-marketing-digitale--at--com-and-dev,2406,Responsable marketing digitale,58,NaN,Com & dev (SSII offshore située a Sahloul Sous...,NaN,NaN,...,webmarketing,marketing,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN
6,225715,14d9f59e-179a-4a55-a31c-d351e36b01e7,junior-net-developer--at--equipe-technique-tun...,12864,Junior .Net Developer,10,NaN,We are looking for a junior .Net developer.\r\...,NaN,1000.0,...,dnn,transact-sql,asp.net,3,mvc,.net,NaN,NaN,NaN,NaN
7,225924,213c812b-9523-418e-9c41-fc9388b5f76b,ingenieurs-devops--at--new-access-tunisie-sarl,12983,Ingénieurs devops,10,NaN,1.1.1 Job Description\r\n\r\n \r\n\r\nAs part ...,NaN,NaN,...,anglais,expérience,NaN,3,NaN,NaN,NaN,NaN,NaN,NaN
8,225860,73fc1f4c-12f7-426c-a6f6-f1c1f06e238f,odoo-python-developer--at--intime-solutions-ma...,15749,Odoo & Python Developer,10,NaN,Who we are :\r\n\r\nWe are a people centered c...,NaN,NaN,...,microservices,css3,python,1,html5,javascript,NaN,NaN,NaN,NaN
9,225860,73fc1f4c-12f7-426c-a6f6-f1c1f06e238f,odoo-python-developer--at--intime-solutions-ma...,15749,Odoo & Python Developer,10,NaN,Who we are :\r\n\r\nWe are a people centered c...,NaN,NaN,...,microservices,css3,python,4,html5,javascript,NaN,NaN,NaN,NaN
10,225150,b17c6c15-de49-46ea-8609-aa02d0eb91de,ied-java-jee--php-symfony--net--ios--android--...,21353,"IED Java JEE, PHP/Symfony, .NET, IOS, Android,...",67,NaN,Bonjour :)\r\n\r\nJe suis à la recherche de pl...,NaN,NaN,...,angular4,ios,php,2,android,java,NaN,NaN,NaN,NaN
11,225823,9fdc906a-9ec2-40b6-8391-d8fcd2ca7f3d,c-c-software-developer--at--primatec-engineeri...,20709,C/C++ Software Developer,58,NaN,"Nowadays, Self-driving or autonomous driving b...",NaN,NaN,...,adas,adaptability,flexibility,4,teamwork,ethernet,c,c++,NaN,NaN
12,223347,fa9bf532-6dd0-4b46-ad6d-1d2b4ff8bf5b,experienced-javascript-developer--at--xtech-22...,11777,Experienced JavaScript developer,10,NaN,Experienced JavaScript developer\r\n\r\nxTECH ...,NaN,1000.0,...,html5,javascript,NaN,4,NaN,NaN,NaN,NaN,NaN,NaN
13,225922,d7354b77-554e-4eee-92dc-c6ef41dbb55f,developpeur-informatique---at--expensya,562,Développeur informatique,10,NaN,"Expensya est une entreprise franco-tunisienne,...",NaN,NaN,...,web,mobile,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN
14,225905,74952a7b-2b2a-4d56-a446-01e163030160,responsable-marketing-digitale--at--com-and-dev,2406,Responsable marketing digitale,58,NaN,Com & dev (SSII offshore située a Sahloul Sous...,NaN,NaN,...,webmarketing,marketing,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN
15,223347,fa9bf532-6dd0-4b46-ad6d-1d2b4ff8bf5b,experienced-javascript-developer--at--xtech-22...,11777,Experienced JavaScript developer,10,NaN,Experienced JavaScript developer\r\n\r\nxTECH ...,NaN,1000.0,...,html5,javascript,NaN,3,NaN,NaN,NaN,NaN,NaN,NaN
16,225922,d7354b77-554e-4eee-92dc-c6ef41dbb55f,developpeur-informatique---at--expensya,562,Développeur informatique,10,NaN,"Expensya est une entreprise franco-tunisienne,...",NaN,NaN,...,web,mobile,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN
17,225860,73fc1f4c-12f7-426c-a6f6-f1c1f06e238f,odoo-python-developer--at--intime-solutions-ma...,15749,Odoo & Python Developer,10,NaN,Who we are :\r\n\r\nWe are a people centered c...,NaN,NaN,...,microservices,css3,python,3,html5,javascript,NaN,NaN,NaN,NaN
18,224244,37ce3e65-0160-4663-9c2d-a83c8771cd20,developpeur-php-symfony--at--proxym-group-224244,1017,Développeur PHP/Symfony,58,NaN,"PROXYM Group, leader dans le secteur IT notam...",NaN,1250.0,...,developpement,développement,reporting,2,web,symfony,git,php,html,css
19,224796,59239852-7e09-47b9-870a-057753011983,developpeur-web--at--kap-it-tunisia-224796,3088,Développeur web,10,NaN,KAP IT révolutionne la collaboration en entrep...,NaN,NaN,...,java,front-end,angular,2,NaN,NaN,NaN,NaN,NaN,NaN
20,224163,c39d3c7e-bcd1-4f88-9771-6e4fdb0d09be,chef-de-projet-technique-h-f-decade-monastir--...,3598,Chef de projet Technique (H/F) DECADE Monastir,58,NaN,Qui nous-sommes ? \r\n\r\nDECADE est un presta...,NaN,NaN,...,java,php,.net,1,NaN,NaN,NaN,NaN,NaN,NaN
21,225150,b17c6c15-de49-46ea-8609-aa02d0eb91de,ied-java-jee--php-symfony--net--ios--android--...,21353,"IED Java JEE, PHP/Symfony, .NET, IOS, Android,...",67,NaN,Bonjour :)\r\n\r\nJe suis à la recherche de pl...,NaN,NaN,...,angular4,ios,php,1,android,java,NaN,NaN,NaN,NaN
22,224163,c39d3c7e-bcd1-4f88-9771-6e4fdb0d09be,chef-de-projet-technique-h-f-decade-monastir--...,3598,Chef de projet Technique (H/F) DECADE Monastir,58,NaN,Qui nous-sommes ? \r\n\r\nDECADE est un presta...,NaN,NaN,...,java,php,.net,3,NaN,NaN,NaN,NaN,NaN,NaN
23,224163,c39d3c7e-bcd1-4f88-9771-6e4fdb0d09be,chef-de-projet-technique-h-f-decade-monastir--...,3598,Chef de projet Technique (H/F) DECADE Monastir,58,NaN,Qui nous-sommes ? \r\n\r\nDECADE est un presta...,NaN,NaN,...,java,php,.net,4,NaN,NaN,NaN,NaN,NaN,NaN
24,224163,c39d3c7e-bcd1-4f88-9771-6e4fdb0d09be,chef-de-projet-technique-h-f-decade-monastir--...,3598,Chef de projet Technique (H/F) DECADE Monastir,58,NaN,Qui nous-sommes ? \r\n\r\nDECADE est un presta...,NaN,NaN,...,java,php,.net,2,NaN,NaN,NaN,NaN,NaN,NaN
25,224244,37ce3e65-0160-4663-9c2d-a83c8771cd20,developpeur-php-symfony--at--proxym-group-224244,1017,Développeur PHP/Symfony,58,NaN,"PROXYM Group, leader dans le secteur IT notam...",NaN,1250.0,...,developpement,développement,reporting,4,web,symfony,git,php,html,css
26,225823,9fdc906a-9ec2-40b6-8391-d8fcd2ca7f3d,c-c-software-developer--at--primatec-engineeri...,20709,C/C++ Software Developer,58,NaN,"Nowadays, Self-driving or autonomous driving b...",NaN,NaN,...,adas,adaptability,flexibility,3,teamwork,ethernet,c,c++,NaN,NaN
27,225266,0eda32ff-2ffe-4402-939a-370fe0271392,controleur-de-gestion-reporting-analyst--at--o...,16406,Contrôleur de Gestion Reporting Analyst,10,NaN,ODDO BHF Tunis est une entreprise de services ...,NaN,NaN,...,reporting,gestion,analyst,2,NaN,NaN,NaN,NaN,NaN,NaN
28,225924,213c812b-9523-418e-9c41-fc9388b5f76b,ingenieurs-devops--at--new-access-tunisie-sarl,12983,Ingénieurs devops,10,NaN,1.1.1 Job Description\r\n\r\n \r\n\r\nAs part ...,NaN,NaN,...,anglais,expérience,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN
29,224244,37ce3e65-0160-4663-9c2d-a83c8771cd20,developpeur-php-symfony--at--proxym-group-224244,1017,Développeur PHP/Symfony,58,NaN,"PROXYM Group, leader dans le secteur IT notam...",NaN,1250.0,...,developpement,développement,reporting,1,web,symfony,git,php,html,css
30,224796,59239852-7e09-47b9-870a-057753011983,developpeur-web--at--kap-it-tunisia-224796,3088,Développeur web,10,NaN,KAP IT révolutionne la collaboration en entrep...,NaN,NaN,...,java,front-end,angular,1,NaN,NaN,NaN,NaN,NaN,NaN
31,225924,213c812b-9523-418e-9c41-fc9388b5f76b,ingenieurs-devops--at--new-access-tunisie-sarl,12983,Ingénieurs devops,10,NaN,1.1.1 Job Description\r\n\r\n \r\n\r\nAs part ...,NaN,NaN,...,anglais,expérience,NaN,4,NaN,NaN,NaN,NaN,NaN,NaN
32,225715,14d9f59e-179a-4a55-a31c-d351e36b01e7,junior-net-developer--at--equipe-technique-tun...,12864,Junior .Net Developer,10,NaN,We are looking for a junior .Net developer.\r\...,NaN,1000.0,...,dnn,transact-sql,asp.net,2,mvc,.net,NaN,NaN,NaN,NaN
33,225860,73fc1f4c-12f7-426c-a6f6-f1c1f06e238f,odoo-python-developer--at--intime-solutions-ma...,15749,Odoo & Python Developer,10,NaN,Who we are :\r\n\r\nWe are a people centered c...,NaN,NaN,...,microservices,css3,python,5,html5,javascript,NaN,NaN,NaN,NaN
34,225860,73fc1f4c-12f7-426c-a6f6-f1c1f06e238f,odoo-python-developer--at--intime-solutions-ma...,15749,Odoo & Python Developer,10,NaN,Who we are :\r\n\r\nWe are a people centered c...,NaN,NaN,...,microservices,css3,python,2,html5,javascript,NaN,NaN,NaN,NaN
35,225924,213c812b-9523-418e-9c41-fc9388b5f76b,ingenieurs-devops--at--new-access-tunisie-sarl,12983,Ingénieurs devops,10,NaN,1.1.1 Job Description\r\n\r\n \r\n\r\nAs part ...,NaN,NaN,...,anglais,expérience,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN
36,225394,6dd6904b-2762-48f3-9947-97434596206d,senior-reactjs-developer--at--weavelines-225394,14035,Senior ReactJS Developer,10,NaN,Company:\r\n\r\nWeaveLines is a digital lab bu...,NaN,NaN,...,redux,reactjs,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN
37,225266,0eda32ff-2ffe-4402-939a-370fe0271392,controleur-de-gestion-reporting-analyst--at--o...,16406,Contrôleur de Gestion Reporting Analyst,10,NaN,ODDO BHF Tunis est une entreprise de services ...,NaN,NaN,...,reporting,gestion,analyst,1,NaN,NaN,NaN,NaN,NaN,NaN
38,223347,fa9bf532-6dd0-4b46-ad6d-1d2b4ff8bf5b,experienced-javascript-developer--at--xtech-22...,11777,Experienced JavaScript developer,10,NaN,Experienced JavaScript developer\r\n\r\nxTECH ...,NaN,1000.0,...,html5,javascript,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN
39,224163,c39d3c7e-bcd1-4f88-9771-6e4fdb0d09be,chef-de-projet-technique-h-f-decade-monastir--...,3598,Chef de projet Technique (H/F) DECADE Monastir,58,NaN,Qui nous-sommes ? \r\n\r\nDECADE est un presta...,NaN,NaN,...,java,php,.net,5,NaN,NaN,NaN,NaN,NaN,NaN
40,225715,14d9f59e-179a-4a55-a31c-d351e36b01e7,junior-net-developer--at--equipe-technique-tun...,12864,Junior .Net Developer,10,NaN,We are looking for a junior .Net developer.\r\...,NaN,1000.0,...,dnn,transact-sql,asp.net,1,mvc,.net,NaN,NaN,NaN,NaN
41,225715,14d9f59e-179a-4a55-a31c-d351e36b01e7,junior-net-developer--at--equipe-technique-tun...,12864,Junior .Net Developer,10,NaN,We are looking for a junior .Net developer.\r\...,NaN,1000.0,...,dnn,transact-sql,asp.net,4,mvc,.net,NaN,NaN,NaN,NaN
42,225823,9fdc906a-9ec2-40b6-8391-d8fcd2ca7f3d,c-c-software-developer--at--primatec-engineeri...,20709,C/C++ Software Developer,58,NaN,"Nowadays, Self-driving or autonomous driving b...",NaN,NaN,...,adas,adaptability,flexibility,1,teamwork,ethernet,c,c++,NaN,NaN
43,225924,213c812b-9523-418e-9c41-fc9388b5f76b,ingenieurs-devops--at--new-access-tunisie-sarl,12983,Ingénieurs devops,10,NaN,1.1.1 Job Description\r\n\r\n \r\n\r\nAs part ...,NaN,NaN,...,anglais,expérience,NaN,5,NaN,NaN,NaN,NaN,NaN,NaN
44,223347,fa9bf532-6dd0-4b46-ad6d-1d2b4ff8bf5b,experienced-javascript-developer--at--xtech-22...,11777,Experienced JavaScript developer,10,NaN,Experienced JavaScript developer\r\n\r\nxTECH ...,NaN,1000.0,...,html5,javascript,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN
45,225394,6dd6904b-2762-48f3-9947-97434596206d,senior-reactjs-developer--at--weavelines-225394,14035,Senior ReactJS Developer,10,NaN,Company:\r\n\r\nWeaveLines is a digital lab bu...,NaN,NaN,...,redux,reactjs,NaN,3,NaN,NaN,NaN,NaN,NaN,NaN
46,225823,9fdc906a-9ec2-40b6-8391-d8fcd2ca7f3d,c-c-software-developer--at--primatec-engineeri...,20709,C/C++ Software Developer,58,NaN,"Nowadays, Self-driving or autonomous driving b...",NaN,NaN,...,adas,adaptability,flexibility,2,teamwork,ethernet,c,c++,NaN,NaN
47,223347,fa9bf532-6dd0-4b46-ad6d-1d2b4ff8bf5b,experienced-javascript-developer--at--xtech-22...,11777,Experienced JavaScript developer,10,NaN,Experienced JavaScript developer\r\n\r\nxTECH ...,NaN,1000.0,...,html5,javascript,NaN,5,NaN,NaN,NaN,NaN,NaN,NaN
48,224796,59239852-7e09-47b9-870a-057753011983,developpeur-web--at--kap-it-tunisia-224796,3088,Développeur web,10,NaN,KAP IT révolutionne la collaboration en entrep...,NaN,NaN,...,java,front-end,angular,4,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
result = df
for i in range(20):
    df1 =pd.read_json("https://www.jobi.tn/api/joboffers/sponsored?limit=50")
    df1.head()
    result = pd.concat([result, df1], sort=False)

In [14]:
saved_result = result
result.head()

,id,uuid,slug,profile_id,title,category_id,collaborators,description,summary,salary_min,...,tags/5,tags/6,tags/7,tags/8,tags/9,company,job_type,location,requirements,tags
0,224796,59239852-7e09-47b9-870a-057753011983,developpeur-web--at--kap-it-tunisia-224796,3088,Développeur web,10,NaN,KAP IT révolutionne la collaboration en entrep...,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,225266,0eda32ff-2ffe-4402-939a-370fe0271392,controleur-de-gestion-reporting-analyst--at--o...,16406,Contrôleur de Gestion Reporting Analyst,10,NaN,ODDO BHF Tunis est une entreprise de services ...,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,225150,b17c6c15-de49-46ea-8609-aa02d0eb91de,ied-java-jee--php-symfony--net--ios--android--...,21353,"IED Java JEE, PHP/Symfony, .NET, IOS, Android,...",67,NaN,Bonjour :)\r\n\r\nJe suis à la recherche de pl...,NaN,NaN,...,java,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,225394,6dd6904b-2762-48f3-9947-97434596206d,senior-reactjs-developer--at--weavelines-225394,14035,Senior ReactJS Developer,10,NaN,Company:\r\n\r\nWeaveLines is a digital lab bu...,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,224244,37ce3e65-0160-4663-9c2d-a83c8771cd20,developpeur-php-symfony--at--proxym-group-224244,1017,Développeur PHP/Symfony,58,NaN,"PROXYM Group, leader dans le secteur IT notam...",NaN,1250.0,...,symfony,git,php,html,css,NaN,NaN,NaN,NaN,NaN

In [17]:
result['salary']=(result.salary_min+result.salary_max)/2

In [31]:
result[['salary_max', 'salary_max', 'salary']]

    salary_max  salary_max       salary
0          NaN         NaN  2283.608491
1          NaN         NaN  2283.608491
2          NaN         NaN  2283.608491
3          NaN         NaN  2283.608491
4       1250.0      1250.0  1250.000000
5          NaN         NaN  2283.608491
6       1000.0      1000.0  1000.000000
7          NaN         NaN  2283.608491
8          NaN         NaN  2283.608491
9          NaN         NaN  2283.608491
10         NaN         NaN  2283.608491
11         NaN         NaN  2283.608491
12      4000.0      4000.0  2500.000000
13         NaN         NaN  2283.608491
14         NaN         NaN  2283.608491
15      4000.0      4000.0  2500.000000
16         NaN         NaN  2283.608491
17         NaN         NaN  2283.608491
18      1250.0      1250.0  1250.000000
19         NaN         NaN  2283.608491
20         NaN         NaN  2283.608491
21         NaN         NaN  2283.608491
22         NaN         NaN  2283.608491
23         NaN         NaN  2283.608491
24         NaN         NaN  2283.608491
25      1250.0      1250.0  1250.000000
26         NaN         NaN  2283.608491
27         NaN         NaN  2283.608491
28         NaN         NaN  2283.608491
29      1250.0      1250.0  1250.000000
..         ...         ...          ...
19         NaN         NaN  2283.608491
20         NaN         NaN  2283.608491
21         NaN         NaN  2283.608491
22         NaN         NaN  2283.608491
23         NaN         NaN  2283.608491
24         NaN         NaN  2283.608491
25      1250.0      1250.0  2283.608491
26         NaN         NaN  2283.608491
27         NaN         NaN  2283.608491
28      4000.0      4000.0  2500.000000
29      1250.0      1250.0  2283.608491
30      4000.0      4000.0  2500.000000
31      4000.0      4000.0  2500.000000
32      1000.0      1000.0  2283.608491
33         NaN         NaN  2283.608491
34         NaN         NaN  2283.608491
35         NaN         NaN  2283.608491
36         NaN         NaN  2283.608491
37         NaN         NaN  2283.608491
38      1000.0      1000.0  1000.000000
39         NaN         NaN  2283.608491
40      1000.0      1000.0  2283.608491
41      1000.0      1000.0  2283.608491
42         NaN         NaN  2283.608491
43         NaN         NaN  2283.608491
44      1000.0      1000.0  2500.000000
45         NaN         NaN  2283.608491
46         NaN         NaN  2283.608491
47      1000.0      1000.0  2500.000000
48         NaN         NaN  2283.608491

[1029 rows x 3 columns]

In [32]:
result['salary_min'].fillna(df['salary_max'],inplace=True)
result['salary_max'].fillna(df['salary_min'],inplace=True)

result['salary']=(result.salary_min+result.salary_max)/2
salary_mean = result.salary.mean()
result['salary'].fillna(salary_mean,inplace=True)

In [34]:
result.head()

,id,uuid,slug,profile_id,title,category_id,collaborators,description,summary,salary_min,...,tags/6,tags/7,tags/8,tags/9,company,job_type,location,requirements,tags,salary
0,224796,59239852-7e09-47b9-870a-057753011983,developpeur-web--at--kap-it-tunisia-224796,3088,Développeur web,10,NaN,KAP IT révolutionne la collaboration en entrep...,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2283.608491
1,225266,0eda32ff-2ffe-4402-939a-370fe0271392,controleur-de-gestion-reporting-analyst--at--o...,16406,Contrôleur de Gestion Reporting Analyst,10,NaN,ODDO BHF Tunis est une entreprise de services ...,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2283.608491
2,225150,b17c6c15-de49-46ea-8609-aa02d0eb91de,ied-java-jee--php-symfony--net--ios--android--...,21353,"IED Java JEE, PHP/Symfony, .NET, IOS, Android,...",67,NaN,Bonjour :)\r\n\r\nJe suis à la recherche de pl...,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2283.608491
3,225394,6dd6904b-2762-48f3-9947-97434596206d,senior-reactjs-developer--at--weavelines-225394,14035,Senior ReactJS Developer,10,NaN,Company:\r\n\r\nWeaveLines is a digital lab bu...,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2283.608491
4,224244,37ce3e65-0160-4663-9c2d-a83c8771cd20,developpeur-php-symfony--at--proxym-group-224244,1017,Développeur PHP/Symfony,58,NaN,"PROXYM Group, leader dans le secteur IT notam...",NaN,1250.0,...,git,php,html,css,NaN,NaN,NaN,NaN,NaN,1250.000000

In [33]:
result.to_csv("jobi_all.csv")